### PR TITLE
Completed javascript-timers.

### PR DESCRIPTION
**Pull request by stefancarrera**
JStime

### CODE REVIEW

**Review by Zhiwutian — CHANGES_REQUESTED** [review]
almost there, just make sure to clear the interval!

**Comment by stefancarrera** [comment]
JStime
Added the clearInterval to both files

**Review by Zhiwutian — CHANGES_REQUESTED** [review]
so in order to clear the interval, you must pass it the intervalId as an argument. Give it another shot!

**Comment by stefancarrera** [comment]
added intervalId as argument

**Review by Zhiwutian — APPROVED** [review]
👍🏼

**Pull request merged**
